### ISSUE TITLE
Linkable does not work with ArraySource models

### ISSUE THREAD

**Issue by ravage84** [lorenzo/linkable#12]
I'm extensivly using the ArrraySource datasource to replicate ENUM data type fields.
This means I have a lot of relations between models from the default datasource and ArraySource based models.

Unfortunately Linkable v1.1.1 does not seem to work with such a setup.

I pressume Linkable does not work accross datasources/databases as https://github.com/lorenzo/linkable/issues/7 indicates.
Containable by the way does, even for deep associations.

**Comment by lorenzo** [comment]
No, linkable's purpose in life is to make database joins. You can't make a database join with a php array.

**Comment by ravage84** [comment]
I realized, that this works with Containable because it **does** separate queries for sub-sub entities, which results in an array based model and datasource specific "query".

**Comment by lorenzo** [comment]
That's correct
